//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SMOSEC.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_group : IAggregateRoot
    {
        public auth_group()
        {
            this.auth_group_permissions = new HashSet<auth_group_permissions>();
            this.auth_user_groups = new HashSet<auth_user_groups>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<auth_group_permissions> auth_group_permissions { get; set; }
        public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }
    }
}
