//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SMOSEC.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public class auth_user : IAggregateRoot
    {
        public auth_user()
        {
            this.auth_user_groups = new HashSet<auth_user_groups>();
            this.auth_user_user_permissions = new HashSet<auth_user_user_permissions>();
            this.django_admin_log = new HashSet<django_admin_log>();
        }
    
        public int id { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public bool is_superuser { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public bool is_staff { get; set; }
        public bool is_active { get; set; }
        public System.DateTime date_joined { get; set; }
    
        public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }
        public virtual ICollection<auth_user_user_permissions> auth_user_user_permissions { get; set; }
        public virtual ICollection<django_admin_log> django_admin_log { get; set; }
    }
}
