//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMOSEC.Domain.Entity
{   
    public class cmdb_asset : IAggregateRoot
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("id")]
        [ForeignKey("cmdb_repairlog")]
        public int id { get; set; }

        public string uuid { get; set; }
        public string IP { get; set; }
        [Required]
        public string sn { get; set; }
        public string asset_number { get; set; }
        [Required]
        public string position { get; set; }
        [Required]
        public short status { get; set; }
        public Nullable<System.DateTime> give_time { get; set; }
        public Nullable<System.DateTime> return_time { get; set; }
        public string remark { get; set; }
        [Required]
        public System.DateTime modify_date { get; set; }

        [Required]
        [ForeignKey("cmdb_assettype")]
        public int asset_type_id { get; set; }
        [Required]
        [ForeignKey("cmdb_brand")]
        public int brand_id { get; set; }
        [Required]
        [ForeignKey("cmdb_machineroom")]
        public int machine_room_id { get; set; }
        [Required]
        [ForeignKey("cmdb_payman")]
        public int pay_man_id { get; set;}


        [ForeignKey("cmdb_project")]
        public Nullable<int> project_id { get; set; }
        [ForeignKey("cmdb_role")]
        public Nullable<int> role_id { get; set; }
        [ForeignKey("cmdb_team")]
        public Nullable<int> team_id { get; set; }
        [ForeignKey("cmdb_useman")]
        public Nullable<int> use_man_id { get; set; }


        public virtual cmdb_assettype cmdb_assettype { get; set; }
        public virtual cmdb_brand cmdb_brand { get; set; }
        public virtual cmdb_machineroom cmdb_machineroom { get; set; }
        public virtual cmdb_payman cmdb_payman { get; set; }
        public virtual cmdb_project cmdb_project { get; set; }
        public virtual cmdb_role cmdb_role { get; set; }
        public virtual cmdb_team cmdb_team { get; set; }
        public virtual cmdb_useman cmdb_useman { get; set; }
        public virtual ICollection<cmdb_assettouselog> cmdb_assettouselog { get; set; }
        public virtual ICollection<cmdb_repairlog> cmdb_repairlog { get; set; }
    }
}
