//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SMOSEC.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    [Table("cmdb_userinfo")]
    public class cmdb_userinfo: IAggregateRoot
    {
        public int id { get; set; }
        public string local_username { get; set; }
        public string local_password { get; set; }
        public string permission { get; set; }
    }
}
