//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SMOSEC.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class django_content_type : IAggregateRoot
    {
        public django_content_type()
        {
            this.auth_permission = new HashSet<auth_permission>();
            this.django_admin_log = new HashSet<django_admin_log>();
        }
    
        public int id { get; set; }
        public string app_label { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<auth_permission> auth_permission { get; set; }
        public virtual ICollection<django_admin_log> django_admin_log { get; set; }
    }
}
